name: Release Next
on:
  push:
    tags:
      - '!v*'
      - 'v*-beta*'

jobs:
  release:
    name: Release
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v1
      - uses: actions/setup-node@v1
        with:
          node-version: '10.16'
          scope: '@rtkwlf'
          registry-url: https://npm.pkg.github.com/
      - name: Install
        run: npm install
      - name: Build
        run: npm run build
      - name: Publish to github packages
        run: npm publish --access public --tag next
        env:
          NODE_AUTH_TOKEN: ${{secrets.GITHUB_TOKEN}}
