name: Release
on:
  push:
    tags:
      - v*
      - '!v*-beta*'

jobs:
  release:
    name: Release to Github Packages and NPM
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v1
      - uses: actions/setup-node@v1
        with:
          node-version: '10.16'
          scope: '@rtkwlf'
          registry-url: https://npm.pkg.github.com/
      - name: Install
        run: npm install
      - name: Build
        run: npm run build
      - name: Publish to github packages
        run: npm publish --access public
        env:
          NODE_AUTH_TOKEN: ${{secrets.GITHUB_TOKEN}}
      - uses: actions/setup-node@v1
        with:
          node-version: '10.16'
          scope: '@rtkwlf'
          registry-url: https://registry.npmjs.com
      - name: Configure .npmrc for publish to npm
        run: 'echo "//registry.npmjs.org/:_authToken=${NODE_AUTH_TOKEN}" > ~/.npmrc'
        env:
          NODE_AUTH_TOKEN: ${{secrets.NPM_AUTH_TOKEN}}
      - name: Publish to npm
        run: npm publish --access public