name: deploy
on: [push]

jobs:
  main-tests:
    name: deploy
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v1
      - uses: actions/setup-node@v1
        with:
          node-version: '10.16'
      - run: npm install
      - run: npm run build
      - run: git status
      - run: git add lib/
      - run: git commit -m "commiting build"
      - run: git push origin aaho-start
