name: Release Next
on:
  push:
    branches:
      - next
      - '!master'

jobs:
  tag:
    name: Create Tag
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v1
      - uses: actions/setup-node@v1
        with:
          node-version: '10.16'
          scope: '@rtkwlf'
      - name: Configure Git
        run: |
          git config --local user.email "action@github.com"
          git config --local user.name "GitHub Action"
      - name: Create tag
        run: npm version prerelease --preid beta
      - name: Push Tag
        uses: ad-m/github-push-action@master
        with:
          branch: 'next'
          tags: true
          github_token: ${{ secrets.GITHUB_TOKEN }}

      release:
        name: Release
        needs: tag
        runs-on: ubuntu-latest
        steps:
          - uses: actions/checkout@v1
          - uses: actions/setup-node@v1
            with:
              node-version: '10.16'
              scope: '@rtkwlf'
          - name: Install
            run: npm install
          - name: Build
            run: npm run build
          - name: Configure .npmrc for publish
            run: 'echo "//registry.npmjs.org/:_authToken=${NODE_AUTH_TOKEN}" > ~/.npmrc'
            env:
              NODE_AUTH_TOKEN: ${{secrets.NPM_AUTH_TOKEN}}
          - name: Publish to npm
            run: npm publish --access public --tag next
  release:
    name: Create Tag
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v1
      - uses: actions/setup-node@v1
        with:
          node-version: '10.16'
          scope: '@rtkwlf'
      - name: Configure Git
        run: |
          git config --local user.email "action@github.com"
          git config --local user.name "GitHub Action"
      - name: Create tag
        run: npm version prerelease --preid beta
      - name: Push Tag
        uses: ad-m/github-push-action@master
        with:
          branch: 'next'
          tags: true
          github_token: ${{ secrets.GITHUB_TOKEN }}
      - name: Create Release
        uses: actions/create-release@v1
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        with:
          tag_name: ${{ github.ref }}
          release_name: Release ${{ github.ref }}
          body: Auto beta release
          draft: false
          prerelease: true


