name: test
on: [tag]

jobs:
  main-tests:
    name: Test and Lint
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v1
      - uses: actions/setup-node@v1
        with:
          node-version: '10.16'
      - run: npm install
      - run: npm test
      - run: npm run lint
