name: Create Beta Tag
on:
  push:
    branches:
      - next
      - '!master'

jobs:
  tag:
    name: Create Tag
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v1
      - name: Configure Git
        run: |
          git config --local user.email "action@github.com"
          git config --local user.name "GitHub Action"
      - name: Create tag
        run: npm version prerelease --preid beta
      - name: Push Tag
        uses: ad-m/github-push-action@master
        with:
          branch: 'next'
          tags: true
          github_token: ${{ secrets.GITHUB_TOKEN }}

